version: '3'
services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uhyu-recommender
    env_file:
      - ./.env
    networks:
      - uhyu-net
    ports:
      - "18000:8000"
networks:
  uhyu-net:
    external: true